### ISSUE TITLE
Cannot push apps after install on Rancher Desktop

### ISSUE THREAD

**Issue by timirnich** [epinio/helm-charts#54] opened 2021-12-23 14:11 UTC
I am installing Epinio on Rancher Desktop
```
helm install --set domain=$EPINIO_SYSTEM_DOMAIN --set skipTraefik=true epinio-installer epinio/epinio-installer
NAME: epinio-installer
LAST DEPLOYED: Thu Dec 23 14:58:44 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
You can get the IP address of your Ingress controller by passing this command:
`kubectl describe svc traefik --namespace traefik | awk '/Ingress/ { print $3 }'`

Make sure your domain points to the IP address of your Ingress controller (1.2.3.4).

To interract with your Epinio installation, you have to download the latest epinio binary https://github.com/epinio/epinio/releases.

Update the api location and credentials with:
`epinio config update`

For more information about Epinio, feel free to checkout https://epinio.io/ and https://docs.epinio.io/.
```

Config update and info look normal after install
```
epinio config update

🚢 Updating the stored credentials from the current cluster
Config: /Users/tim/.config/epinio/config.yaml

✔️  Ok
```
and 
```
epinio info

✔️  Epinio Environment
Platform: k3s
Kubernetes Version: v1.20.12+k3s1
Epinio Version: v0.3.2
```

Trying to push the 12Factor app fails
```
epinio push -n twelve-factor

🚢 About to push an application with the given setup
Manifest: <<Defaults>>
Name: twelve-factor
Source Origin: /Users/tim/Documents/src/timirnich-epinio-example-12factor
Target Namespace: workspace
Builder: paketobuildpacks/builder:full

⚠️  Hit Enter to continue or Ctrl+C to abort (deployment will continue automatically in 5 seconds)


Create the application resource ...

Collecting the application sources ...

Uploading application code ...
error pushing app to server: can't upload archive: server status code: Internal Server Error
{"errors":[{"status":500,"title":"ensuring bucket: 503 Service Unavailable","details":"uploading the application sources blob\nServer Backtrace: 503 Service Unavailable\nensuring bucket\ngithub.com/epinio/epinio/internal/s3manager.(*Manager).Upload\n\t/go/src/github.com/epinio/internal/s3manager/s3manager.go:176\ngithub.com/epinio/epinio/internal/api/v1/application.Controller.Upload\n\t/go/src/github.com/epinio/internal/api/v1/application/upload.go:73\ngithub.com/epinio/epinio/internal/api/v1.errorHandler.func1\n\t/go/src/github.com/epinio/internal/api/v1/router.go:36\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-contrib/sessions.Sessions.func1\n\t/go/pkg/mod/github.com/gin-contrib/sessions@v0.0.4/sessions.go:54\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2879\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1930\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"}]}
```

I see the the minio tenant pod is in CrashLoopBackoff:
```
kubectl get pods -A
NAMESPACE          NAME                                           READY   STATUS             RESTARTS   AGE
kube-system        helm-install-traefik-kqvfl                     0/1     Completed          0          42m
kube-system        local-path-provisioner-5ff76fc89d-4vwgf        1/1     Running            1          42m
kube-system        metrics-server-86cbb8457f-ttgs6                1/1     Running            1          42m
kube-system        coredns-6488c6fcc6-7khdh                       1/1     Running            1          42m
kube-system        svclb-traefik-xf9bs                            2/2     Running            2          42m
kube-system        traefik-6f9cbd9bd4-m2sp6                       1/1     Running            1          42m
kube-image         builder-dc7wc                                  2/2     Running            0          13m
cert-manager       cert-manager-cainjector-748dc889c5-cpxsc       1/1     Running            0          10m
kubed              kubed-8b79869b8-clwxz                          1/1     Running            0          10m
cert-manager       cert-manager-666cb5c4b-mlhwn                   1/1     Running            0          10m
cert-manager       cert-manager-webhook-995c5c5b6-zvmpv           1/1     Running            0          10m
linkerd            linkerd-destination-5c458f5444-v6j2j           2/2     Running            0          10m
linkerd            linkerd-identity-586d498c64-px8nn              2/2     Running            0          10m
linkerd            linkerd-controller-f8cbf79d4-nmtvs             2/2     Running            0          10m
linkerd            linkerd-proxy-injector-6bb6df967c-krphk        2/2     Running            0          10m
linkerd            linkerd-sp-validator-754577f988-2tj8d          2/2     Running            0          10m
linkerd            linkerd-install-rnb8w                          0/1     Completed          0          10m
minio-operator     minio-operator-6675cf89c8-qnj7x                1/1     Running            0          10m
epinio-registry    registry-998dd7888-465v8                       2/2     Running            0          10m
tekton-pipelines   tekton-pipelines-controller-5c5bc999bf-w7qth   1/1     Running            0          9m58s
tekton-pipelines   tekton-pipelines-webhook-5555c4b6cd-gkxq6      1/1     Running            0          9m58s
epinio             epinio-server-75f46fc955-phqz4                 2/2     Running            0          9m24s
minio-epinio       tenant1-ss-0-0                                 1/2     CrashLoopBackOff   6          9m41s
linkerd            linkerd-heartbeat-1640268480-rcmpw             1/1     Running            0          92s
```

```
kubectl logs tenant1-ss-0-0 -c minio -n minio-epinio
ERROR Unable to validate passed arguments in MINIO_ARGS:env+tls://zahdTEFdQabFD8Jinn97:9FMBCGThkZaiRw0XcSK5gmS7TU6p1FS0oU0MwIJ4@operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/minio-epinio/tenant1: Get "https://operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/minio-epinio/tenant1?key=MINIO_ARGS": context deadline exceeded
```

**Comment by jimmykarily** [comment] 2022-01-10 09:33
@timirnich what OS are you running rancher-desktop on? We need this info to be able to reproduce the problem.

**Comment by juadk** [comment] 2022-01-18 14:41
It should be MacOS because we can not reach that point on Linux (https://github.com/epinio/epinio/issues/1116).

**Comment by timirnich** [comment] 2022-01-18 15:57
It is MacOS indeed - apologies for the delayed response.

**Comment by juadk** [comment] 2022-01-18 16:29
Anyway, it works for me on MacOS:
I used: 
- RD 1.00-beta.1 + containerd + kubernetes 1.21.5
- epinio-installer helm chart 0.3.5

More info [here](https://github.com/epinio/epinio/issues/1116)

**Comment by juadk** [comment] 2022-01-19 08:55
Let's close the issue, @timirnich please, feel free to open it again if needed.

**Closed by juadk** 2022-01-19 08:55 UTC
